### ISSUE TITLE
error in SIFTflowc2f.m

### ISSUE THREAD

**Issue by smmdream** [seungryong/DASC#2]
Dear author,
when I run the main.m, I got the error 
![2019-04-18 17-38-43屏幕截图](https://user-images.githubusercontent.com/10106222/56352037-fd421800-6200-11e9-8fcb-f4bab2dd6c0a.png)
I don't know why.
And I can't understand the second USAGE of readme, setup SIFTflow code, I don't know how to finish this setup, can you give me some idea to deal the problem.

**Comment by seungryong** [comment]
Hi, it seems like the compile error. You first should compile "mexDiscreteFlow.cpp". You can download this in the original SIFT flow code at https://people.csail.mit.edu/celiu/SIFTflow/. Thank you.
